--- #YAML:1.0
name:               Parse-CPAN-Packages-Fast
version:            0.05_50
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    CPAN::DistnameInfo:  0
    CPAN::Version:       0
    PerlIO::gzip:        0
resources:
    repository:  git://github.com/eserte/parse-cpan-packages-fast.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
